services:

  ## Service utilisé au démarrage uniquement pour installer les dépendances nécessaires
  ## au fonctionnement de notre backend
  installBackend:
    image: node
    working_dir: /app
    volumes:
      - ./backend/app:/app
    command: "npm install"

  ## Service utilisé au démarrage uniquement pour installer les dépendances nécessaires
  ## au fonctionnement de notre backend
  installFrontend:
    image: node
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: "yarn install"
